import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("Seeding tenders...")

  await prisma.tender.createMany({
    skipDuplicates: true,
    data: [
      {
        id: "t-001",
        title: "A57 Road Resurfacing and Drainage Improvement — 3 Year Framework",
        buyer: "National Highways",
        buyerType: "highways",
        location: "Sheffield, South Yorkshire",
        region: "Yorkshire & Humber",
        value: 850_000,
        valueMax: 1_200_000,
        deadline: new Date("2026-07-18"),
        publishedDate: new Date("2026-06-01"),
        category: "highways",
        type: "framework",
        status: "open",
        recommendation: "recommended",
        opportunityScore: 87,
        eligibilityScore: 82,
        smeFlag: true,
        description: "National Highways seeks an SME-capable contractor to deliver resurfacing, drainage and line marking works on the A57 corridor. Strong social value weighting.",
        cpvCode: "45233141-9",
        reference: "NH/YH/2026/0714",
        socialValueWeighting: 20,
        framework: "Regional Highways Maintenance Framework",
        requiredDocuments: ["Public Liability Insurance", "Employers Liability Insurance", "ISO 9001", "StreetWorks Licence", "Method Statement"],
        missingDocuments: [],
        insuranceRequired: ["public-liability", "employers-liability"],
        accreditationsRequired: ["iso-9001", "safe-contractor"],
        deliveryRisk: "low",
        financialRisk: "low",
        bidEffort: "medium",
        winProbability: 72,
        estimatedBidCost: 3_500,
        socialValueRequirements: "10% local employment, 5% apprenticeships",
        buyerNotes: "Buyer prefers incumbent with prior National Highways experience. Social value is 20% of total score.",
        recommendedAction: "Bid — strong match. Lead with social value and highways experience.",
      },
      {
        id: "t-002",
        title: "Winter Maintenance Services — Gritting and Snow Clearance",
        buyer: "Stockport Metropolitan Borough Council",
        buyerType: "local-authority",
        location: "Stockport, Greater Manchester",
        region: "North West",
        value: 420_000,
        deadline: new Date("2026-07-05"),
        publishedDate: new Date("2026-06-10"),
        category: "highways",
        type: "contract",
        status: "closing-soon",
        recommendation: "recommended",
        opportunityScore: 91,
        eligibilityScore: 88,
        smeFlag: true,
        description: "Stockport Council requires a provider for gritting, snow ploughing and ice prevention across its primary and secondary road network for 3 years.",
        cpvCode: "90620000-9",
        reference: "SMBC/HW/2026/WM-01",
        socialValueWeighting: 15,
        requiredDocuments: ["Public Liability Insurance", "Employers Liability Insurance", "Gritting Equipment Schedule", "Method Statement"],
        missingDocuments: [],
        insuranceRequired: ["public-liability", "employers-liability", "vehicle"],
        accreditationsRequired: ["safe-contractor"],
        deliveryRisk: "low",
        financialRisk: "low",
        bidEffort: "low",
        winProbability: 68,
        estimatedBidCost: 1_800,
        recommendedAction: "Strong fit with your North West presence. Submit before deadline.",
      },
      {
        id: "t-003",
        title: "Facilities Management — Multi-Site Maintenance",
        buyer: "NHS Greater Manchester",
        buyerType: "nhs",
        location: "Greater Manchester",
        region: "North West",
        value: 1_800_000,
        deadline: new Date("2026-08-30"),
        publishedDate: new Date("2026-06-15"),
        category: "facilities",
        type: "contract",
        status: "open",
        recommendation: "maybe",
        opportunityScore: 61,
        eligibilityScore: 55,
        smeFlag: false,
        description: "NHS Greater Manchester ICB seeks an FM contractor to deliver planned and reactive maintenance across 8 community health sites. Includes M&E, civil works and grounds.",
        cpvCode: "50700000-2",
        reference: "NHSGM/FM/2026/014",
        socialValueWeighting: 25,
        requiredDocuments: ["Public Liability £5m", "Professional Indemnity", "ISO 9001", "ISO 14001", "Cyber Essentials", "Social Value Strategy"],
        missingDocuments: ["Cyber Essentials", "ISO 14001"],
        insuranceRequired: ["public-liability", "employers-liability", "professional-indemnity"],
        accreditationsRequired: ["iso-9001", "iso-14001", "cyber-essentials"],
        deliveryRisk: "medium",
        financialRisk: "medium",
        bidEffort: "high",
        winProbability: 38,
        estimatedBidCost: 12_000,
        recommendedAction: "Address ISO 14001 and Cyber Essentials gaps before bidding. Consider consortium.",
      },
      {
        id: "t-004",
        title: "Street Cleaning and Litter Collection — Annual Contract",
        buyer: "Tameside Metropolitan Borough Council",
        buyerType: "local-authority",
        location: "Tameside, Greater Manchester",
        region: "North West",
        value: 280_000,
        deadline: new Date("2026-07-22"),
        publishedDate: new Date("2026-06-08"),
        category: "cleaning",
        type: "contract",
        status: "open",
        recommendation: "maybe",
        opportunityScore: 55,
        eligibilityScore: 70,
        smeFlag: true,
        description: "Tameside MBC requires a street cleaning and litter collection service for town centres and residential areas. The contract includes seasonal deep-cleans.",
        requiredDocuments: ["Public Liability Insurance", "Employers Liability Insurance", "Fleet list"],
        missingDocuments: [],
        insuranceRequired: ["public-liability", "employers-liability"],
        accreditationsRequired: [],
        deliveryRisk: "low",
        financialRisk: "low",
        bidEffort: "low",
        winProbability: 42,
        estimatedBidCost: 1_200,
        recommendedAction: "Outside core sector — only bid if capacity allows.",
      },
      {
        id: "t-005",
        title: "Construction of 12 Affordable Homes — Design & Build",
        buyer: "Trafford Housing Trust",
        buyerType: "housing",
        location: "Sale, Trafford",
        region: "North West",
        value: 2_400_000,
        deadline: new Date("2026-09-15"),
        publishedDate: new Date("2026-06-20"),
        category: "construction",
        type: "contract",
        status: "open",
        recommendation: "not-recommended",
        opportunityScore: 34,
        eligibilityScore: 40,
        smeFlag: false,
        description: "Trafford Housing Trust invites tenders for the design and build of 12 affordable homes on a brownfield site. JCT Design & Build contract.",
        requiredDocuments: ["Professional Indemnity £2m", "Public Liability £5m", "ISO 9001", "Constructionline Gold", "Structural Warranty Provider"],
        missingDocuments: ["Professional Indemnity", "Constructionline Gold"],
        insuranceRequired: ["public-liability", "employers-liability", "professional-indemnity"],
        accreditationsRequired: ["constructionline", "iso-9001"],
        deliveryRisk: "high",
        financialRisk: "high",
        bidEffort: "high",
        winProbability: 15,
        estimatedBidCost: 18_000,
        recommendedAction: "Significant eligibility gaps. Do not bid without Constructionline Gold and PI insurance.",
      },
    ],
  })

  console.log("Seeding buyers...")

  const buyersData = [
    {
      name: "National Highways",
      type: "highways",
      region: "National",
      annualSpend: 45_000_000,
      upcomingRenewals: ["Regional Maintenance Framework — Q3 2026"],
      knownSuppliers: ["Tarmac", "Amey", "Kier Highways"],
      nextTenderExpected: new Date("2026-07-01"),
    },
    {
      name: "Stockport Metropolitan Borough Council",
      type: "local-authority",
      region: "North West",
      annualSpend: 3_200_000,
      upcomingRenewals: ["Winter Maintenance — June 2026"],
      knownSuppliers: ["Ringway", "Colas"],
      nextTenderExpected: new Date("2026-06-15"),
    },
    {
      name: "NHS Greater Manchester",
      type: "nhs",
      region: "North West",
      annualSpend: 12_000_000,
      upcomingRenewals: ["FM Contract — August 2026"],
      knownSuppliers: ["Mitie", "ISS"],
    },
  ]

  for (const buyer of buyersData) {
    await prisma.buyer.upsert({
      where: { id: buyer.name.replace(/\s+/g, "-").toLowerCase() },
      create: { id: buyer.name.replace(/\s+/g, "-").toLowerCase(), ...buyer },
      update: {},
    })
  }

  console.log("Seed complete.")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
